import type { TeachingDeck } from '@/types/teaching-decks'

export const UNIT6_DECKS: TeachingDeck[] = [
  {
    id: 'unit6-edge-cloud-ai-security',
    unit: 6,
    session: 18,
    title: 'Unit 6 · From Connected Device to Intelligent IoT System',
    subtitle: 'A self-study final-class deck spanning edge vs cloud, complete cloud architecture, Edge AI / TinyML, security, and one real-world architecture case study.',
    icon: '🧠',
    minutes: 60,
    essentialQuestion: 'How should an IoT architect decide where data is processed, where intelligence runs, and how the complete system is secured?',
    objectives: [
      'Connect the learning journey from sensing and controllers to communication, cloud, intelligence and secure actuation',
      'Choose edge or cloud processing using latency, bandwidth, privacy, resilience and scale',
      'Trace a complete IoT cloud architecture from device telemetry to storage, analytics, dashboard and command',
      'Explain where Edge AI and TinyML fit and distinguish model training from on-device inference',
      'Explain authentication, encryption, TLS and DTLS in the context of IoT device communication',
      'Design and justify a complete real-world IoT architecture independently',
    ],
    equipment: ['Laptop, tablet or phone', 'IoT at CHRIST Unit 6 deck', 'Notebook or architecture sketching tool', 'Optional ESP32 / Raspberry Pi examples for reference'],
    preparation: [
      'Students should complete Units 1–5 or review the recap slide before beginning.',
      'No hardware build is required: Unit 6 is intentionally self-study and architecture-focused.',
      'Encourage students to research unfamiliar protocols or platform services before answering the final case study.',
    ],
    slides: [
      {
        id: 'unit6-recap',
        kind: 'hook',
        label: 'One-slide IoT journey',
        title: 'From the physical world to a trusted decision',
        subtitle: 'Everything from Units 1–5 becomes one connected system before Unit 6 asks where intelligence belongs and how the system stays trustworthy.',
        durationMinutes: 5,
        teacherPrompt: 'Reveal the stages in order. Ask students to say which earlier unit gave them the knowledge needed at each stage.',
        studentOutcome: 'Students can describe IoT as an end-to-end system rather than a collection of sensors and boards.',
        flow: [
          { label: '1 · Sense', detail: 'Unit 1–2: sensors convert physical conditions such as temperature, motion, light or distance into electrical/digital evidence.', packet: 'Physical world → measurement' },
          { label: '2 · Compute', detail: 'Unit 2–4: Arduino, ESP32 or Raspberry Pi reads inputs, applies local logic and drives outputs.', packet: 'measurement → controller state' },
          { label: '3 · Communicate', detail: 'Unit 3–4: Wi-Fi, BLE and other networks carry data using application protocols such as MQTT, HTTP or CoAP.', packet: 'device → network → protocol message' },
          { label: '4 · Integrate', detail: 'Unit 4–5: gateways, services, storage, dashboards and applications turn messages into a usable IoT service.', packet: 'telemetry → service → user' },
          { label: '5 · Decide + Act', detail: 'Unit 5: analytics, rules and human decisions send a safe command back to the physical system.', packet: 'decision → command → actuator' },
          { label: '6 · Trust', detail: 'Unit 6: choose edge/cloud placement, add AI where justified, and secure identity plus communication.', packet: 'right place + right intelligence + right security' },
        ],
        cards: [
          { title: 'WHAT?', kicker: 'System purpose', body: 'What physical problem is being observed or controlled?', accent: 'navy' },
          { title: 'HOW?', kicker: 'System path', body: 'How does evidence travel from sensor to decision and back to an actuator?', accent: 'saffron' },
          { title: 'WHY?', kicker: 'Engineering reason', body: 'Why is each controller, network, protocol, processing location and security control needed?', accent: 'green' },
        ],
      },
      {
        id: 'unit6-route',
        kind: 'plan',
        label: 'Self-study route',
        title: 'Study four ideas, then become the IoT architect',
        durationMinutes: 3,
        teacherPrompt: 'Explain that the goal is not memorising definitions. Every topic will become a design decision in the final case study.',
        studentOutcome: 'Students understand that the final evidence is a justified system architecture.',
        timeline: [
          { minutes: '0–8', title: 'Reconnect Units 1–5', teacherAction: 'Trace one complete IoT loop.', studentEvidence: 'Explain sensor → decision → actuator.' },
          { minutes: '8–20', title: 'Edge vs Cloud', teacherAction: 'Compare placement decisions.', studentEvidence: 'Justify one local and one cloud decision.' },
          { minutes: '20–32', title: 'Cloud architecture', teacherAction: 'Trace telemetry through services.', studentEvidence: 'Name the role of every stage.' },
          { minutes: '32–42', title: 'Edge AI / TinyML', teacherAction: 'Separate training and inference.', studentEvidence: 'Choose where inference should run.' },
          { minutes: '42–52', title: 'IoT security', teacherAction: 'Connect identity and encrypted transport.', studentEvidence: 'Explain authentication, encryption, TLS and DTLS.' },
          { minutes: '52–60', title: 'Case study', teacherAction: 'Stop teaching and let students design.', studentEvidence: 'Produce a complete architecture with trade-off reasoning.' },
        ],
      },
      {
        id: 'unit6-edge-cloud',
        kind: 'compare',
        label: 'What · How · Why',
        title: 'Edge Computing vs Cloud Computing',
        subtitle: 'The important question is not which one is better. It is which decisions belong where.',
        durationMinutes: 7,
        teacherPrompt: 'Use the same sensor event twice: once as a safety-critical event and once as a historical trend. Ask why the processing location changes.',
        studentOutcome: 'Students choose processing location using engineering constraints rather than habit.',
        cards: [
          { title: 'Edge Computing', kicker: 'Near the data source', body: 'Processing runs on or near the device: ESP32, Raspberry Pi, gateway or local server. It reduces dependence on remote connectivity and can react quickly.', accent: 'green' },
          { title: 'Cloud Computing', kicker: 'Remote shared services', body: 'Processing, storage and analytics run in scalable remote infrastructure. It is useful for fleet management, historical analysis, dashboards and heavy computation.', accent: 'blue' },
          { title: 'Hybrid IoT', kicker: 'Most real systems', body: 'Immediate decisions stay local while selected telemetry, history and fleet-wide analytics go to cloud services.', accent: 'gold' },
          { title: 'Decision factors', kicker: 'Choose intentionally', body: 'Latency, bandwidth, privacy, Internet availability, energy, compute limits, storage, scale and failure tolerance drive the choice.', accent: 'saffron' },
        ],
        poll: {
          question: 'A platform-edge warning must still work if the Internet connection fails. Where should the first safety decision happen?',
          options: [
            { label: 'Only in the cloud', feedback: 'That creates an avoidable dependency on remote connectivity for an immediate safety decision.' },
            { label: 'At the edge, then report to cloud', feedback: 'Correct. Keep the immediate decision local and use the cloud for history, alerts and wider analysis.', correct: true },
            { label: 'Only in the mobile app', feedback: 'A phone app should not be the only place a time-sensitive physical safety decision exists.' },
          ],
        },
      },
      {
        id: 'unit6-edge-cloud-lab',
        kind: 'activity',
        label: 'Placement lab',
        title: 'Where should this computation happen?',
        durationMinutes: 5,
        teacherPrompt: 'Students tap each scenario and state edge, cloud or hybrid before reading the explanation.',
        studentOutcome: 'Students can defend placement choices with at least two constraints.',
        flow: [
          { label: 'Fire / hazard alarm', detail: 'Use edge or device logic for the immediate alarm so action does not wait for Internet access. Send events to the cloud for history and remote notification.', packet: 'sensor → local rule → alarm | event → cloud' },
          { label: '30-day farm trend', detail: 'Cloud storage and analytics are useful because the question depends on history across many samples rather than a millisecond response.', packet: 'soil telemetry → cloud database → trend' },
          { label: 'Security camera', detail: 'A hybrid design can analyse frames locally and send only important events or selected evidence, reducing bandwidth and improving privacy.', packet: 'camera → edge inference → event metadata → cloud' },
          { label: 'Fleet maintenance', detail: 'Local anomaly checks can protect each machine while cloud analytics compares patterns across the whole fleet.', packet: 'machine edge alert + fleet cloud analysis' },
        ],
        checklist: [
          'I considered latency',
          'I considered Internet failure',
          'I considered bandwidth',
          'I considered privacy',
          'I considered device compute limits',
          'I considered system scale',
        ],
      },
      {
        id: 'unit6-cloud-architecture',
        kind: 'concept',
        label: 'Complete system',
        title: 'Complete IoT Cloud Architecture',
        subtitle: '“ESP32 → Cloud” hides the services that actually make an IoT platform useful.',
        durationMinutes: 7,
        teacherPrompt: 'Tap one stage at a time. After each stage ask what would break if that stage did not exist.',
        studentOutcome: 'Students can trace one telemetry message through a complete cloud architecture.',
        flow: [
          { label: '1 · Sensor / Actuator', detail: 'The physical layer observes the world or changes it. Measurements must have meaning, units and a known source.', packet: 'temperature = 31.7 °C' },
          { label: '2 · Device', detail: 'ESP32, Arduino or Raspberry Pi reads sensors, timestamps or packages data, applies local logic and handles actuators.', packet: '{deviceId, value, unit, observedAt}' },
          { label: '3 · Connectivity + Protocol', detail: 'Wi-Fi, cellular or another network carries MQTT, HTTP, CoAP or another application message.', packet: 'MQTT PUBLISH /lab/room04/temp' },
          { label: '4 · Edge / Gateway', detail: 'Optional gateway filters, aggregates, translates protocols, buffers data during outages or runs local decisions.', packet: '10 raw readings → 1 useful event' },
          { label: '5 · Ingestion', detail: 'An MQTT broker, API gateway or IoT hub authenticates endpoints and receives device traffic reliably.', packet: 'message accepted from device-04' },
          { label: '6 · Processing / Rules', detail: 'Rules, functions or streams validate data and detect events such as thresholds, anomalies or state changes.', packet: 'if temp > limit → warning' },
          { label: '7 · Storage', detail: 'Databases and object storage preserve current state, time-series history, configuration and larger files.', packet: 'room04 + timestamp + value' },
          { label: '8 · Analytics / AI', detail: 'Historical and fleet-level processing finds trends, predicts conditions or supports decisions.', packet: 'trend rising for 20 min' },
          { label: '9 · Application', detail: 'Dashboards, mobile apps and alerts present evidence to the people who must decide or act.', packet: 'WARNING · room04 overheating' },
          { label: '10 · Command path', detail: 'Approved actions travel back through the platform to the device, which should report its final state as evidence.', packet: 'fan=ON → acknowledgement → state=ON' },
        ],
      },
      {
        id: 'unit6-message-journey',
        kind: 'activity',
        label: 'Follow one message',
        title: 'Watch one IoT event travel end to end',
        durationMinutes: 5,
        teacherPrompt: 'Ask students to predict the next stage before tapping it. Emphasise that commands require an acknowledgement loop.',
        studentOutcome: 'Students can explain both telemetry and command directions.',
        flow: [
          { label: 'Measure', detail: 'A temperature sensor produces 42 °C and the device adds identity plus time.', packet: 'device-17 | 42 °C | 10:15:03' },
          { label: 'Publish', detail: 'The device publishes telemetry through MQTT over the network.', packet: 'PUBLISH factory/device-17/temp' },
          { label: 'Ingest', detail: 'The broker authenticates the connection and routes the message to interested services.', packet: 'authenticated device-17 → rules service' },
          { label: 'Decide', detail: 'A rule marks the condition as abnormal and stores the event.', packet: 'state=WARNING' },
          { label: 'Notify', detail: 'The dashboard shows the event and an authorised operator requests cooling.', packet: 'command: fan=ON' },
          { label: 'Acknowledge', detail: 'The device performs the command and reports the observed final state. This closes the evidence loop.', packet: 'reportedState: fan=ON' },
        ],
      },
      {
        id: 'unit6-edge-ai',
        kind: 'concept',
        label: 'What · How · Why',
        title: 'Edge AI and TinyML',
        subtitle: 'AI becomes an IoT design tool when inference is placed where it improves the system.',
        durationMinutes: 6,
        teacherPrompt: 'Separate training from inference. Students often assume an ML model must contact the cloud every time it predicts.',
        studentOutcome: 'Students explain TinyML and identify when on-device inference is useful.',
        cards: [
          { title: 'Edge AI', kicker: 'Inference near the source', body: 'An edge computer such as a Raspberry Pi or capable embedded device runs an AI model close to the sensor instead of sending every raw input to the cloud.', accent: 'blue' },
          { title: 'TinyML', kicker: 'ML on constrained devices', body: 'TinyML techniques make compact models practical on microcontrollers so tasks such as keyword, gesture or vibration classification can run locally.', accent: 'green' },
          { title: 'Training', kicker: 'Usually powerful compute', body: 'Datasets are prepared and models are trained or fine-tuned on laptops, workstations or cloud infrastructure.', accent: 'gold' },
          { title: 'Inference', kicker: 'Can run at the edge', body: 'The deployed model receives new sensor data and produces a prediction. This is the stage that can move onto an edge device.', accent: 'saffron' },
        ],
        flow: [
          { label: 'Collect data', detail: 'Gather labelled examples that represent the real conditions the system must recognise.', packet: 'normal vibration / abnormal vibration' },
          { label: 'Train model', detail: 'Use suitable compute to learn patterns from the dataset and evaluate accuracy on unseen examples.', packet: 'dataset → trained model' },
          { label: 'Optimise', detail: 'Reduce memory or computation where needed, while checking the effect on model quality.', packet: 'model → compact deployment model' },
          { label: 'Deploy', detail: 'Place the model on an ESP32-class device, Raspberry Pi or gateway that can execute it within system constraints.', packet: 'model file → edge device' },
          { label: 'Infer + act', detail: 'New sensor readings produce a local prediction that can trigger an immediate action and optionally report the event to the cloud.', packet: 'vibration → anomaly → stop / alert' },
        ],
      },
      {
        id: 'unit6-tinyml-lab',
        kind: 'compare',
        label: 'AI placement lab',
        title: 'Does this AI need the cloud?',
        durationMinutes: 4,
        teacherPrompt: 'Ask students to justify the answer using latency, privacy, bandwidth, energy and model complexity.',
        studentOutcome: 'Students choose device, edge gateway or cloud inference deliberately.',
        cards: [
          { title: 'Keyword trigger', body: 'A small local keyword recogniser can avoid streaming continuous audio and can still work offline.', accent: 'green' },
          { title: 'Camera analytics', body: 'A Raspberry Pi or other edge accelerator may process video locally and upload only selected events.', accent: 'blue' },
          { title: 'Fleet forecasting', body: 'Cloud AI may be appropriate when the prediction needs months of data from many devices.', accent: 'gold' },
        ],
        poll: {
          question: 'A machine must stop immediately when its vibration pattern becomes dangerous, even if the network is unavailable. Which design is strongest?',
          options: [
            { label: 'Send every sample to cloud AI first', feedback: 'That makes the safety response depend on network and cloud availability.' },
            { label: 'Run local inference and report the event to cloud', feedback: 'Correct. Keep the urgent inference local, then use cloud history and fleet analytics.', correct: true },
            { label: 'Store samples and analyse next week', feedback: 'Useful for long-term analysis, but it does not satisfy the immediate protection requirement.' },
          ],
        },
      },
      {
        id: 'unit6-security',
        kind: 'concept',
        label: 'What · How · Why',
        title: 'Authentication, Encryption, TLS and DTLS',
        subtitle: 'Security begins with two questions: “Who is communicating?” and “Can anyone else understand or alter the communication?”',
        durationMinutes: 6,
        teacherPrompt: 'Use a fake device attempting to publish a command. Ask which control answers identity and which protects data in transit.',
        studentOutcome: 'Students distinguish authentication from encryption and connect TLS/DTLS to protected transport.',
        cards: [
          { title: 'Authentication', kicker: 'Who are you?', body: 'The system verifies the identity of a user, device or server using credentials such as keys, tokens or certificates before granting access.', accent: 'saffron' },
          { title: 'Encryption', kicker: 'Protect the message', body: 'Encryption transforms readable data into protected ciphertext so intercepted traffic is not directly understandable without the required key.', accent: 'green' },
          { title: 'TLS', kicker: 'Secure connection', body: 'TLS authenticates peers as configured, negotiates cryptographic protection and secures application traffic commonly carried over reliable transports such as TCP.', accent: 'blue' },
          { title: 'DTLS', kicker: 'TLS-like security for datagrams', body: 'DTLS provides comparable transport-security goals for datagram communication, making it relevant to UDP-based protocols such as CoAP deployments.', accent: 'gold' },
        ],
        flow: [
          { label: 'Identity', detail: 'Before trusting telemetry or commands, the platform verifies the device or server identity.', packet: 'device certificate / credential' },
          { label: 'Handshake', detail: 'The endpoints establish security parameters and keys for the protected session.', packet: 'authenticate + negotiate keys' },
          { label: 'Encrypted traffic', detail: 'Application messages travel as protected ciphertext rather than readable plaintext.', packet: 'Door=OPEN → protected bytes' },
          { label: 'Authorisation', detail: 'After identity is known, policy still decides what that identity is allowed to publish, subscribe, read or control.', packet: 'device-17 may publish telemetry; may not control device-22' },
        ],
      },
      {
        id: 'unit6-tls-dtls',
        kind: 'compare',
        label: 'Secure the packet',
        title: 'Match the application protocol to protected transport',
        durationMinutes: 4,
        teacherPrompt: 'Have students read each stack from top to bottom and explain why CoAP deployments often discuss DTLS while HTTP/MQTT deployments commonly discuss TLS.',
        studentOutcome: 'Students can place TLS and DTLS correctly in a simplified IoT protocol stack.',
        cards: [
          { title: 'HTTPS', kicker: 'HTTP + TLS', body: 'HTTP application traffic is protected by TLS when used as HTTPS.', accent: 'blue' },
          { title: 'MQTT over TLS', kicker: 'Broker connection', body: 'MQTT clients can establish protected connections to a broker using TLS and server/client authentication as required.', accent: 'green' },
          { title: 'CoAP + DTLS', kicker: 'Datagram-oriented option', body: 'CoAP commonly uses UDP, where DTLS can provide transport security for datagram communication.', accent: 'gold' },
        ],
        poll: {
          question: 'An attacker can see network packets but does not possess the session keys. Which control is intended to stop the payload being readable in transit?',
          options: [
            { label: 'Authentication only', feedback: 'Authentication verifies identity, but confidentiality requires cryptographic protection of the traffic.' },
            { label: 'Encryption through the secure transport', feedback: 'Correct. TLS or DTLS can protect application data in transit as part of a secure session.', correct: true },
            { label: 'A larger database', feedback: 'Storage size has no direct role in protecting packets on the network.' },
          ],
        },
      },
      {
        id: 'unit6-architect-checklist',
        kind: 'exit',
        label: 'Architect checklist',
        title: 'Before calling an IoT design complete, answer these questions',
        durationMinutes: 3,
        teacherPrompt: 'Students should use this checklist as the rubric for the final case study. Do not provide one “correct architecture”; require justified trade-offs.',
        studentOutcome: 'Students have a reusable architecture checklist for future IoT projects.',
        checklist: [
          'What physical problem must be sensed or controlled?',
          'Which sensors and actuators are required?',
          'Which controller or gateway fits the workload?',
          'How will devices communicate and which protocol carries the data?',
          'Which decisions belong on-device, at the edge or in the cloud?',
          'Does AI add value? If yes, where should inference run?',
          'Where are current state, history and large files stored?',
          'How do users see evidence and issue authorised commands?',
          'How are devices/users authenticated and traffic encrypted?',
          'What happens when Internet or cloud connectivity fails?',
          'How does the design change when the system grows from one device to many?',
        ],
      },
      {
        id: 'unit6-final-case-study',
        kind: 'activity',
        label: 'Final case study',
        title: 'Design a Smart Railway Station Safety & Assistance System',
        subtitle: 'Research what you need, make engineering choices, and justify the architecture. The application will turn your answers into a visual system path.',
        durationMinutes: 5,
        teacherPrompt: 'Do not solve it for students. Ask “why?” after every technology choice and require graceful behaviour when the Internet is unavailable.',
        studentOutcome: 'Each student produces an end-to-end IoT architecture that connects sensing, communication, edge/cloud processing, AI, security and actuation.',
        caseStudy: {
          scenario: 'A railway station wants an intelligent IoT system that detects people near restricted/platform-edge areas, identifies obstacles and abnormal conditions, assists navigation, notifies control-room staff, stores important events, and continues essential safety functions when Internet connectivity is unstable. Cameras or AI may be used, but continuous raw video should not be uploaded unless the design can justify it.',
          challenge: 'Design the complete IoT architecture. Your answer must explain WHAT each layer does, HOW information moves, and WHY each major technology or processing location was chosen.',
          requirements: [
            'Include sensors, controllers/gateways, connectivity and at least one actuator or user-facing response.',
            'Separate immediate edge/device decisions from cloud responsibilities.',
            'Explain whether Edge AI / TinyML is useful and where inference should run.',
            'Show the cloud ingestion, processing, storage, analytics/dashboard and command path.',
            'Use authentication and encrypted communication; explain where TLS or DTLS fits.',
            'Describe safe behaviour when Internet/cloud connectivity is unavailable.',
            'Explain how the design could scale beyond a single prototype.',
          ],
          fields: [
            { id: 'problem', label: '1 · Problem & success condition', prompt: 'What exact station problem are you solving, and what observable outcome means the system succeeds?', placeholder: 'Example: detect a person entering a restricted edge zone and warn locally before reporting the event.' },
            { id: 'sensors', label: '2 · Sensors', prompt: 'Which sensors or data sources are needed and what does each measure?', placeholder: 'Camera, ultrasonic / ToF, environmental sensor, BLE beacon...' },
            { id: 'controllers', label: '3 · Controller / gateway', prompt: 'Choose ESP32, Raspberry Pi, gateway or a combination. Why does each device belong in the architecture?', placeholder: 'ESP32 for distributed sensing; Raspberry Pi gateway for local vision inference...' },
            { id: 'communication', label: '4 · Connectivity & protocol', prompt: 'How do components communicate? Choose links and application protocols and justify them.', placeholder: 'BLE for nearby beacon discovery, Wi-Fi/Ethernet backhaul, MQTT for telemetry...' },
            { id: 'edge', label: '5 · Edge decisions', prompt: 'Which decisions must happen locally even if the Internet is unavailable?', placeholder: 'Restricted-zone detection, obstacle warning, local alarm...' },
            { id: 'ai', label: '6 · Edge AI / TinyML', prompt: 'Where could AI improve the system? State whether inference runs on a microcontroller, Raspberry Pi/gateway or cloud, and why.', placeholder: 'Run person/zone detection on the edge; send only events and selected evidence...' },
            { id: 'cloud', label: '7 · Cloud architecture', prompt: 'Describe ingestion, processing/rules, storage, analytics/dashboard and the return command path.', placeholder: 'MQTT broker → rules → time-series/event storage → dashboard → authorised command...' },
            { id: 'security', label: '8 · Security', prompt: 'How are devices/users authenticated, what is encrypted, and where would TLS or DTLS be used?', placeholder: 'Unique device identity, least-privilege permissions, MQTT over TLS...' },
            { id: 'failure', label: '9 · Failure & resilience', prompt: 'What happens when Internet or cloud connectivity fails?', placeholder: 'Local safety continues; gateway buffers events; sync resumes after reconnect...' },
            { id: 'scale', label: '10 · Scale & evidence', prompt: 'What changes when the deployment grows to many platforms/devices, and what evidence will prove the system is working?', placeholder: 'Device registry, topic hierarchy, monitoring, health status, acknowledgements...' },
          ],
          reflectionQuestions: [
            'Why did you place each important decision at device, edge or cloud?',
            'Which part of your design protects people even when the Internet is unavailable?',
            'How do you know a remote command actually happened on the physical device?',
            'Which raw data can be avoided or reduced to improve privacy and bandwidth?',
          ],
        },
      },
    ],
  },
]

export function getUnit6Deck(id: string): TeachingDeck | undefined {
  return UNIT6_DECKS.find((deck) => deck.id === id)
}
