import { BoardThumb } from '@/components/simulator/BoardArt'
import { ComponentThumb } from '@/components/simulator/ComponentArt'
import { BOARDS } from '@/lib/simulator/boards'
import type { BoardId, ComponentId } from '@/types/simulator'

export function CircuitCanvas({ boardId, sensor, actuator, step, running, fault, labelsVisible }: { boardId: BoardId; sensor: ComponentId; actuator: ComponentId; step: number; running: boolean; fault: boolean; labelsVisible: boolean }) {
  const Wire = ({ show, color, label }: { show: boolean; color: string; label: string }) => show ? <div className="flex items-center gap-2"><span className={`h-1 flex-1 rounded-full ${color} ${running ? 'hardware-current' : ''}`}/>{labelsVisible && <span className="w-20 text-[9px] font-mono uppercase text-christ-navy/50">{label}</span>}</div> : <div className="h-4 border-t border-dashed border-christ-navy/15"/>
  return <section aria-label="Progressive circuit canvas" className="relative overflow-hidden rounded-2xl border border-christ-navy/10 bg-[radial-gradient(#d9dee6_1px,transparent_1px)] bg-[size:18px_18px] p-5"><div className="absolute right-3 top-3 rounded-full bg-white/90 px-3 py-1 font-mono text-[9px] uppercase tracking-wider text-christ-navy/60">Workbench · not to scale</div><div className="mt-7 grid grid-cols-[1fr_1.25fr_1fr] items-center gap-4"><div className="text-center"><div className="flex h-24 items-center justify-center"><ComponentThumb componentId={sensor} size={100}/></div><b className="text-xs">DHT11 sensor</b></div><div className="space-y-5"><Wire show={step >= 1} color={fault ? 'bg-red-500' : 'bg-slate-700'} label="GND / return"/><Wire show={step >= 2} color={fault ? 'bg-red-500' : 'bg-amber-400'} label="power / energy"/><Wire show={step >= 3} color="bg-sky-500" label="data / signal"/><Wire show={step >= 4} color="bg-violet-500" label="output / logic"/></div><div className="text-center"><div className="flex h-44 items-center justify-center"><BoardThumb board={BOARDS[boardId]} size={165}/></div><b className="text-xs">{BOARDS[boardId].name}</b></div></div>{step >= 4 && <div className="mx-auto mt-2 flex w-44 items-center justify-center rounded-xl bg-white/90 p-2"><ComponentThumb componentId={actuator} size={62}/><span className={`h-3 w-3 rounded-full ${running && !fault ? 'bg-red-500 shadow-[0_0_12px_#ef4444]' : 'bg-red-950'}`}/><span className="ml-2 text-[10px] font-semibold">Alert LED + 220Ω</span></div>}</section>
}
