import type { HardwareComponent } from '@/types/hardware'

const future = (item: Omit<HardwareComponent, 'status' | 'simulationAvailable'>): HardwareComponent => ({ ...item, status: 'future', simulationAvailable: false })
const electrical = (supplyVoltage: string, logicVoltage = 'See module/datasheet', cautions: string[] = []) => ({ supplyVoltage, logicVoltage, recommendedGpioCurrentMa: 0, cautions })

export const HARDWARE_COMPONENT_CATALOGUE: HardwareComponent[] = [
  { id: 'led', name: '5 mm LED', category: 'actuator', status: 'complete', lessonId: 'led-current-limiting', simulationAvailable: false, summary: 'Polarised light-emitting diode for learning safe digital indication.', pinout: [{ pin: 'anode', role: 'Current enters through the longer lead', polarity: 'positive', notes: 'Connect toward GPIO through a resistor.' }, { pin: 'cathode', role: 'Current return; flat side/shorter lead', polarity: 'negative', notes: 'Connect to ground in this lesson.' }], electrical: electrical('About 2 V forward voltage for a typical red LED', 'Driven from 3.3 V or 5 V through a resistor', ['Never connect directly across a supply or GPIO.']), requiredSupportingParts: ['220–330 Ω resistor'] },
  { id: 'resistor', name: 'Current-limiting resistor', category: 'passive', status: 'complete', lessonId: 'led-current-limiting', simulationAvailable: false, summary: 'Limits LED and GPIO current.', pinout: [{ pin: 'lead-1', role: 'Either end', polarity: 'not-polarised', notes: 'Series connection.' }, { pin: 'lead-2', role: 'Either end', polarity: 'not-polarised', notes: 'Series connection.' }], electrical: electrical('Chosen by Ohm’s law', 'Not applicable', ['Check resistance and adequate power rating.']), requiredSupportingParts: [] },
  future({ id: 'push-button', name: 'Momentary push button', category: 'input', summary: 'Digital human input.', pinout: [{ pin: 'contacts', role: 'Normally-open contact pairs', notes: 'Identify internally common legs with a meter.' }], electrical: electrical('3.3–5 V signal circuit'), requiredSupportingParts: ['Pull-up or pull-down resistor (internal where supported)'] }),
  future({ id: 'potentiometer-ldr', name: 'Potentiometer or LDR divider', category: 'input', summary: 'Variable analog voltage source.', pinout: [{ pin: 'signal', role: 'Divider midpoint to ADC', notes: 'Pi requires an external ADC.' }], electrical: electrical('Match ADC reference', 'Never exceed ADC input range'), requiredSupportingParts: ['Fixed divider resistor for LDR', 'External ADC for Raspberry Pi'] }),
  future({ id: 'dht22', name: 'DHT22', category: 'sensor', summary: 'Digital temperature and humidity sensor.', pinout: [{ pin: 'VCC/DATA/GND', role: 'Power, single-wire data, return', notes: 'Bare sensors generally require a DATA pull-up.' }], electrical: electrical('Per exact module datasheet'), requiredSupportingParts: ['DATA pull-up when not fitted to module'] }),
  future({ id: 'bme280', name: 'BME280', category: 'sensor', summary: 'I²C/SPI temperature, humidity and pressure sensor.', pinout: [{ pin: 'VIN/GND/SDA/SCL', role: 'Power and I²C bus', notes: 'Module regulator/level shifting varies.' }], electrical: electrical('Verify bare sensor versus breakout'), requiredSupportingParts: ['I²C pull-ups if absent'] }),
  future({ id: 'hc-sr04', name: 'HC-SR04 ultrasonic sensor', category: 'sensor', summary: 'Time-of-flight distance module.', pinout: [{ pin: 'VCC/TRIG/ECHO/GND', role: 'Power, trigger, return pulse, ground', notes: 'ECHO is commonly 5 V logic.' }], electrical: electrical('Typically 5 V', 'Level-shift ECHO for 3.3 V GPIO', ['Do not feed a 5 V ECHO into ESP32 or Pi.']), requiredSupportingParts: ['ECHO voltage divider or level shifter'] }),
  future({ id: 'pir', name: 'PIR motion module', category: 'sensor', summary: 'Detects changes in infrared radiation.', pinout: [{ pin: 'VCC/OUT/GND', role: 'Power, digital motion output, ground', notes: 'Confirm module output voltage.' }], electrical: electrical('Module-specific'), requiredSupportingParts: [] }),
  future({ id: 'soil-moisture', name: 'Soil-moisture sensor', category: 'sensor', summary: 'Measures a moisture-correlated soil property.', pinout: [{ pin: 'VCC/AO/DO/GND', role: 'Module-dependent analog/digital interface', notes: 'Resistive probes corrode and are not direct volumetric calibration.' }], electrical: electrical('Module-specific'), requiredSupportingParts: ['External ADC for Raspberry Pi when using AO'] }),
  future({ id: 'servo', name: 'Hobby servo', category: 'actuator', summary: 'Position-controlled actuator.', pinout: [{ pin: 'V+/signal/GND', role: 'Motor supply, pulse input, common return', notes: 'Use an external supply sized for stall current.' }], electrical: electrical('Servo-specific external supply', 'Logic pulse per servo specification', ['Do not power a loaded servo from a GPIO pin.']), requiredSupportingParts: ['External supply', 'Common ground', 'Bulk capacitor'] }),
  future({ id: 'relay-module', name: 'Relay module', category: 'interface', summary: 'Galvanically switched load interface.', pinout: [{ pin: 'VCC/IN/GND; COM/NO/NC', role: 'Control side and isolated contacts', notes: 'Isolation depends on module wiring.' }], electrical: electrical('Module-specific coil/control voltage'), requiredSupportingParts: ['Rated enclosure and protection for load'], }),
  future({ id: 'driver-dc-motor', name: 'Driver-controlled DC motor', category: 'actuator', summary: 'DC motor operated through a transistor or H-bridge.', pinout: [{ pin: 'driver inputs/outputs/supply', role: 'Logic control and separate motor-current path', notes: 'Never drive motor directly from GPIO.' }], electrical: electrical('Motor and driver-specific', 'GPIO-compatible driver input', ['Account for stall current and inductive transients.']), requiredSupportingParts: ['Motor driver', 'Flyback protection', 'External motor supply', 'Common ground'] }),
  future({ id: 'buzzer', name: 'Buzzer', category: 'actuator', summary: 'Audible indication; active and passive types behave differently.', pinout: [{ pin: '+/−', role: 'Polarised drive on many modules', notes: 'Check active/passive and current rating.' }], electrical: electrical('Part-specific'), requiredSupportingParts: ['Transistor driver if current exceeds GPIO budget'] }),
  future({ id: 'i2c-display', name: 'I²C display', category: 'interface', summary: 'Addressed text or graphics output.', pinout: [{ pin: 'VCC/GND/SDA/SCL', role: 'Power and I²C bus', notes: 'Check pull-up rail and address.' }], electrical: electrical('Module-specific', 'Bus pull-ups must be GPIO-safe'), requiredSupportingParts: ['Level shifter where bus voltage is incompatible'] }),
]

export const HARDWARE_COMPONENT_BY_ID = Object.fromEntries(HARDWARE_COMPONENT_CATALOGUE.map((component) => [component.id, component]))
