/**
 * Generates a paste-ready SQL seed (supabase/seed_content.sql) from the
 * subject YAML files — mirrors scripts/seed-subjects.ts exactly, for cases
 * where running the Node seeder isn't possible (e.g. setting up from the
 * Supabase SQL editor on a phone). Idempotent: every statement upserts.
 *
 * Run: npx tsx scripts/gen-seed-sql.ts
 */

import * as fs from 'fs'
import * as path from 'path'
import * as yaml from 'js-yaml'
import { SubjectSchema } from '../content/subjects/_schema'
import type { SubjectYAML } from '../content/subjects/_schema'

const CONTENT_DIR = path.join(__dirname, '../content/subjects')
const OUT_FILE = path.join(__dirname, '../supabase/seed_content.sql')

// Dollar-quoting sidesteps all apostrophe/quote escaping in course text.
const TAG = '$iot_seed$'
const q = (value: string): string => {
  if (value.includes('iot_seed')) throw new Error('content collides with dollar-quote tag')
  return `${TAG}${value}${TAG}`
}
const qOrNull = (value: string | null | undefined): string =>
  value === null || value === undefined ? 'null' : q(value)
const jsonOrNull = (value: unknown): string =>
  value === null || value === undefined ? 'null' : `${q(JSON.stringify(value))}::jsonb`

function emitSubject(parsed: unknown, subject: SubjectYAML): string {
  const lines: string[] = []
  const slug = subject.slug

  lines.push(`-- Subject: ${subject.name}`)
  lines.push(
    `insert into subjects (slug, name, description, year, semester, config)
values (${q(slug)}, ${q(subject.name)}, ${qOrNull(subject.description)}, ${qOrNull(subject.year)}, ${qOrNull(subject.semester)}, ${jsonOrNull(parsed)})
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  year = excluded.year,
  semester = excluded.semester,
  config = excluded.config;`,
  )

  for (const unit of subject.units) {
    lines.push('')
    lines.push(`-- Unit ${unit.number}: ${unit.title}`)
    lines.push(
      `insert into units (subject_id, number, title, hours, icon, color_hex)
values ((select id from subjects where slug = ${q(slug)}), ${unit.number}, ${q(unit.title)}, ${unit.hours ?? 'null'}, ${qOrNull(unit.icon)}, ${qOrNull(unit.color)})
on conflict (subject_id, number) do update set
  title = excluded.title,
  hours = excluded.hours,
  icon = excluded.icon,
  color_hex = excluded.color_hex;`,
    )

    for (const session of unit.sessions) {
      lines.push(
        `insert into sessions (unit_id, number, title, hours, topics, keywords, case_study, tools, assignment, no_hw_alternative)
values (
  (select u.id from units u join subjects s on s.id = u.subject_id where s.slug = ${q(slug)} and u.number = ${unit.number}),
  ${session.number}, ${q(session.title)}, ${session.hours ?? 'null'},
  ${jsonOrNull(session.topics)}, ${jsonOrNull(session.keywords)}, ${jsonOrNull(session.case_study)},
  ${jsonOrNull(session.tools)}, ${jsonOrNull(session.assignment)}, ${qOrNull(session.no_hw_alternative)}
)
on conflict (unit_id, number) do update set
  title = excluded.title,
  hours = excluded.hours,
  topics = excluded.topics,
  keywords = excluded.keywords,
  case_study = excluded.case_study,
  tools = excluded.tools,
  assignment = excluded.assignment,
  no_hw_alternative = excluded.no_hw_alternative;`,
      )
    }
  }

  return lines.join('\n')
}

function main(): void {
  const files = fs
    .readdirSync(CONTENT_DIR)
    .filter((f) => f.endsWith('.yaml') && !f.startsWith('_'))

  const blocks: string[] = [
    '-- ════════════════════════════════════════════════════════════════',
    '-- IoT at CHRIST — course content seed (generated by scripts/gen-seed-sql.ts)',
    '-- Equivalent to `npm run seed`. Idempotent — safe to re-run anytime.',
    '-- ════════════════════════════════════════════════════════════════',
    '',
  ]

  for (const file of files) {
    const parsed = yaml.load(fs.readFileSync(path.join(CONTENT_DIR, file), 'utf8'))
    const result = SubjectSchema.safeParse(parsed)
    if (!result.success) {
      console.error(`❌ ${file}: validation failed`)
      result.error.errors.forEach((e) => console.error(`   ${e.path.join('.')} — ${e.message}`))
      process.exitCode = 1
      continue
    }
    blocks.push(emitSubject(parsed, result.data))
    const sessions = result.data.units.reduce((sum, u) => sum + u.sessions.length, 0)
    console.log(`✅ ${file}: ${result.data.units.length} units, ${sessions} sessions`)
  }

  blocks.push('')
  blocks.push('-- Verification: unit and session counts per subject')
  blocks.push(`select s.slug, count(distinct u.id) as units, count(se.id) as sessions
from subjects s
left join units u on u.subject_id = s.id
left join sessions se on se.unit_id = u.id
group by s.slug;`)

  fs.writeFileSync(OUT_FILE, blocks.join('\n') + '\n')
  console.log(`\nWrote ${OUT_FILE}`)
}

main()
